# Generated by Django 5.0.3 on 2024-03-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyApp', '0008_rename_balance_profile_total_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='currency',
            field=models.CharField(choices=[('GBP', 'British Pound'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='GBP', max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='total_balance',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
    ]
